drop table if exists test CASCADE;
create table test
(
    id bigint generated by default as identity,
    name varchar(30),
    primary key (id)
);

drop table if exists users CASCADE;
create table users
(
    userid varchar(50) not null primary key,
    region_id integer not null,
    userpw varchar(100) not null,
    gender char(1),
    age integer,
    username varchar(50),
    profile_image varchar(100),
    phoneNumber varchar(20),
    signup_date DATE
);

drop table if exists student CASCADE;
create table student
(
    studentid integer not null auto_increment primary key,
    userid varchar(50) not null,
    region_id integer not null,
    range varchar(50),
    yail varchar(50),
    time TIME,
    category varchar(50),
    class varchar(50),
    academic varchar(50),
    foreign key (userid) references users(userid)
);

drop table if exists teacher CASCADE;
create table teacher
(
    teacherid integer not null auto_increment primary key,
    userid varchar(50) not null,
    region_id integer not null,
    range varchar(50),
    yail date,
    time TIME,
    comment varchar(100),
    category varchar(50),
    class varchar(50),
    academic varchar(50),
    foreign key (userid) references users(userid)
);

drop table if exists region CASCADE;
create table region
(
    region_id integer not null auto_increment primary key,
    region_depth1 varchar(50) not null,
    region_depth2 varchar(50) not null,
    region_depth3 varchar(50) not null
);